// <auto-generated />
namespace ec.Reservation.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class makeIdLong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makeIdLong));
        
        string IMigrationMetadata.Id
        {
            get { return "201911041354184_makeIdLong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
